# Generated by Django 3.1.7 on 2021-03-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainno', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('no_of_coaches', models.IntegerField()),
                ('FC_seats', models.IntegerField()),
                ('SC_seats', models.IntegerField()),
                ('is_sleeper', models.BooleanField(default=False)),
                ('sleeper_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trains.trains')),
            ],
        ),
    ]
