# Generated by Django 3.1.7 on 2021-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trains',
            old_name='FC_seats',
            new_name='FC_coaches',
        ),
        migrations.RenameField(
            model_name='trains',
            old_name='SC_seats',
            new_name='SC_coaches',
        ),
        migrations.RenameField(
            model_name='trains',
            old_name='sleeper_seats',
            new_name='sleeper_coaches',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='is_sleeper',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='no_of_coaches',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
