# Generated by Django 3.1.7 on 2021-04-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0002_auto_20210416_2310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('coach_type', models.CharField(max_length=15)),
                ('seat_source', models.CharField(max_length=100)),
                ('seat_destination', models.CharField(max_length=100)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='seats.passenger')),
                ('trainid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='trains.trains')),
            ],
        ),
    ]
