# Generated by Django 3.1.7 on 2021-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
