# Generated by Django 3.1.7 on 2021-04-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
